version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/app/Fluxo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      test-dependencies:
        patterns:
          - "NUnit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.*"
          - "Moq"
      serilog:
        patterns:
          - "Serilog*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
